name: botctracker
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/characters/trouble_brewing.txt
    - assets/characters/bad_moon_rising.txt
    - assets/characters/sects_and_violets.txt
    - assets/characters/all_characters.txt
    - assets/images/splash_logo.png
  
  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel/Cinzel-VariableFont_wght.ttf

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/splash_logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/splash_logo.png"