// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3dTEANKlH9_6ZC1J9ZqaSoK63LPi6PX0',
    appId: '1:472172044713:web:810e9d1b8a4a9d59cca4b8',
    messagingSenderId: '472172044713',
    projectId: 'botctracker-6db74',
    authDomain: 'botctracker-6db74.firebaseapp.com',
    storageBucket: 'botctracker-6db74.firebasestorage.app',
    measurementId: 'G-0VE5S598YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNqiG2hsVXB708da8_MYHLi5KL8NoRnJw',
    appId: '1:472172044713:android:7a1c4acdbc7b98c4cca4b8',
    messagingSenderId: '472172044713',
    projectId: 'botctracker-6db74',
    storageBucket: 'botctracker-6db74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq-XUjd2Kf37SjiIASH8BC8Cj9QQ0QqhA',
    appId: '1:472172044713:ios:d7a56c6f1c3c2615cca4b8',
    messagingSenderId: '472172044713',
    projectId: 'botctracker-6db74',
    storageBucket: 'botctracker-6db74.firebasestorage.app',
    iosBundleId: 'com.example.botctracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq-XUjd2Kf37SjiIASH8BC8Cj9QQ0QqhA',
    appId: '1:472172044713:ios:d7a56c6f1c3c2615cca4b8',
    messagingSenderId: '472172044713',
    projectId: 'botctracker-6db74',
    storageBucket: 'botctracker-6db74.firebasestorage.app',
    iosBundleId: 'com.example.botctracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3dTEANKlH9_6ZC1J9ZqaSoK63LPi6PX0',
    appId: '1:472172044713:web:ecbac1dcc5708f33cca4b8',
    messagingSenderId: '472172044713',
    projectId: 'botctracker-6db74',
    authDomain: 'botctracker-6db74.firebaseapp.com',
    storageBucket: 'botctracker-6db74.firebasestorage.app',
    measurementId: 'G-CQ039DVPVY',
  );
}
